{
 "title": "Experiment",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "data_source", "query": "influxdb" },
   {
    "name": "application",
    "query": "SHOW TAG VALUES FROM \"testRuns\" WITH KEY = \"project\""
   },
   {
    "name": "year",
    "query": "SHOW TAG VALUES FROM \"testRuns\" WITH KEY = \"year\" WHERE project=~ /^$application$/"
   },
   {
    "name": "quarter",
    "query": "SHOW TAG VALUES FROM \"testRuns\" WITH KEY = \"quarter\" WHERE project=~ /^$application$/ AND year=~ /^$year$/ "
   },
   {
    "name": "release",
    "query": "SHOW TAG VALUES FROM \"testRuns\" WITH KEY = \"release\" WHERE project=~ /^$application$/ AND year=~ /^$year$/ AND quarter=~ /^$quarter$/ "
   }
  ]
 },
 "panels": [
  {
   "title": "Test Runs per Application",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_project",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(test_name) FROM testRuns  WHERE project=~ /^$application$/ AND year=~ /^$year$/ AND quarter=~ /^$quarter$/ AND release=~ /^$release$/ GROUP BY project",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Test Runs per Users",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 10, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_username",
     "groupBy": [
      { "params": [ "username" ], "type": "tag" }
     ],
     "measurement": "testRuns",
     "query": "SELECT count(test_name) FROM testRuns  WHERE project=~ /^$application$/ AND year=~ /^$year$/ AND quarter=~ /^$quarter$/ AND release=~ /^$release$/ GROUP BY username",
     "select": [
      [
       { "params": [ "test_name" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "time($__interval)", "operator": "=", "value": "select tag value" }
     ]
    }
   ]
  },
  {
   "title": "Test Run Details",
   "type": "table",
   "gridPos": { "h": 9, "w": 21, "x": 0, "y": 7 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT time,test_name,project,release,username FROM testRuns  WHERE project=~ /^$application$/ AND year=~ /^$year$/ AND quarter=~ /^$quarter$/ AND release=~ /^$release$/ ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Test Run Count",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 3, "x": 21, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(test_name) FROM testRuns  WHERE project=~ /^$application$/ AND year=~ /^$year$/ AND quarter=~ /^$quarter$/ AND release=~ /^$release$/ ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}